name: Push Gsheet Trades to Bigquery

on:
  #schedule:
   # - cron: '5 22 * * 1-5'  # Runs Mon-Fri at 10:05 PM UTC i.e 03:35 AM IST
  workflow_dispatch:       # Allow manual run

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Authenticate to GCP
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_KEY_JSON }}        

      - name: Run ETL script
        run: python push_backup_gsheet_trades_to_bigquery.py
